console.log("Hello World!\n")
console.log("Ayaan Ahammad!\n")
console.log("Ashmaan Ahammad!\n")
console.log("Aafiah Fathima!\n")
console.log("Aizah Fathima!\n")
console.log("This is sample!\n")
console.log("This is with GIT GUI commit!\n")
